server:
  port: ${SERVER_PORT:8012}
  servlet:
    context-path: /api-third-part/v1

grpc:
  server:
    port: ${GRPC_SERVER_PORT:8212}
    enableKeepAlive: true
    permitKeepAliveWithoutCalls: true
    keepAliveTime: ${GRPC_SERVER_KEEP_ALIVE_TIME:60}
    keepAliveTimeout: ${GRPC_SERVER_KEEP_ALIVE_TIMEOUT:20}

logging:
  file:
    name: api-third-part.log
  level:
    root: ${LOGGING_LEVEL:info}